name: flutter_rotary_passcode
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  local_hero:
    git:
      url: https://github.com/mkobuolys/local_hero.git
      ref: mark-needs-paint-error-fix
  rflutter_alert: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
     - images/
